chore: Update maxLabelSize to avoid disrupting UI
hoophq/hoop pull request #453
Opened 2024-08-27 13:17 UTC by andriosrobert

2024-08-27 14:40 UTC, sandromello requested changes
This change will also impact the size of the script which could lead to more complain from users. I think it's best to create a different constant or apply the truncate logic directly in the group list.

2024-08-27 21:18 UTC, andriosrobert commented
> This change will also impact the size of the script which could lead to more complain from users. I think it's best to create a different constant or apply the truncate logic directly in the group list.

@sandromello nice catch, that should fix

2024-08-27 21:23 UTC, sandromello commented
LGTM!  @andriosrobert just make sure to change the PR to "Ready for review" if you want to merge it.

2024-08-29 14:58 UTC, andriosrobert commented
@sandromello still see merging is blocked

2024-08-29 15:28 UTC, sandromello approved these changes

2024-08-29 15:30 UTC, merged