[FEAT] Database schema in the Gateway
hoophq/hoop pull request #578
Opened 2024-11-29 22:05 UTC by rogefm

- Create 2 endpoints to get information from a database connection
  - Endpoint to GET databases;
  - Endpoint to GET schema and indexes;
- Create and improve all queries to get database schema;
- Remove all database schema logic from frontend and start to get the database schema information from Gateway;
- Provide for the connections of the types Mongo and Postgres to interact with all databases available;

2024-12-02 16:00 UTC, sandromello requested changes

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/helpers.go
> +	"github.com/gin-gonic/gin"
Remove this unused import

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +
Rewrite every comment to English please.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +		c.JSON(http.StatusRequestTimeout, gin.H{"message": "Request timed out"})
The more appropriate status code is bad request for this case, because it failed to return the proper time defined by the server. A 408 status code is usually sent when the connection with the http client is lost which is not the case.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +			}
Since you're using the function `parseCommandOutput`, just move this whole block logic to this function which will be more clean.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +			dbName = getEnvValue(connEnvs, "envvar:DB")
Refactor to use one line instead: 
```go
(...)
case pb.ConnectionTypePostgres, case pb.ConnectionTypeMSSQL, pb.ConnectionTypeMySQL:
  dbName = getEnvValue(connEnvs, "envvar:DB")
```

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +			dbName = getEnvValue(connEnvs, "envvar:SID")
Is this correct (`envvar:SID`) or it's a typo?

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +		switch pb.ToConnectionType(conn.Type, conn.SubType.String) {
Add a scoped variable as:
```go
connType := pb.ToConnectionType(conn.Type, conn.SubType.String)
```

And then just re-use it throughout this handler.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +	}
This is just for analytics or adding logic in the gateway to prevent execution based in the user agent.
The following statement should be enough if there isn't any particular reason to provide a custom user agent.

```go
userAgent := apiutils.NormalizeUserAgent(c.Request.Header.Values)
```

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +		connType := pb.ToConnectionType(conn.Type, conn.SubType.String)
You're using this function 3 times for the same structure, just use a single time in the top of your handler and then re-use it here.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +		c.JSON(http.StatusRequestTimeout, gin.H{"message": "Request timed out"})
The more appropriate status code is bad request for this case, because it failed to return the proper time defined by the server. A 408 status code is usually sent when the connection with the http client is lost which is not the case.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +			c.JSON(http.StatusInternalServerError, gin.H{"message": fmt.Sprintf("failed to get schema: %s", outcome.Output)})
There's a lot of conditions that may happen here which are not considered an internal error. I recommend to left the http status code as 400 for now and later on improving with more granular ones.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +func parseMongoDBSchema(output string) (SchemaResponse, error) {
There's a lot of things going on here, could you provide some basic unit tests? Having tests will help us to catch errors throughout the lifecycle of this feature.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +func parseSQLSchema(output string, connType pb.ConnectionType) (SchemaResponse, error) {
There's a lot of things going on here, could you provide some basic unit tests? Having tests will help us to catch errors throughout the lifecycle of this feature.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +	dbName := c.Query("database")
You must validate this input to be a valid database, because it's being used to as the introspection query to avoid any injections.

I think something that validates lower, upper cases, `-`,  `_` and numbers should be enough

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +//	@Router			/connections/{nameOrID}/databases/{database}/schema [get]
The route is incorrect here.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/connections/connections.go
> +}
API types should be in the openapi package: `gateway/api/openapi/openapi.go`. Make sure to document the types properly and give proper examples to them.

2024-12-02 16:00 UTC, sandromello commented on gateway/api/server.go
> +	r.GET("/connections/:nameOrID/schema",
Use plural here: `/schemas`

2024-12-02 21:59 UTC, rogefm commented on gateway/api/connections/connections.go
> +			dbName = getEnvValue(connEnvs, "envvar:SID")
It's correct; that is what I found necessary for using Oracle in the past. We can change it in the future if needed.d.

2024-12-03 17:24 UTC, sandromello approved these changes

2024-12-03 17:24 UTC, merged