chore(sentry) add sentry to webapp
hoophq/hoop pull request #579
Opened 2024-11-29 22:38 UTC by mtmr0x

2024-12-02 11:16 UTC, sandromello commented on .github/workflows/release.yml
> +        run: export WEBAPP_VERSION=$(awk -F"'" '{printf "%s", $2}' webapp/src/webapp/version.js)
This step won't work as you expect.
- You must expose the environment variable by appending the key=value in the `$GITHUB_ENV` file. [Reference](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)
- It won't preserve the environment variable across jobs, therefore you need to add this step at the `publish-release` job

You'll need to extract the tarball to obtain the webapp version. I think using the version of the gateway (`GIT_TAG`) would be more appropriate and straightforward.

2024-12-02 12:54 UTC, mtmr0x commented on .github/workflows/release.yml
> +        run: export WEBAPP_VERSION=$(awk -F"'" '{printf "%s", $2}' webapp/src/webapp/version.js)
Hey @sandromello thanks for raising these points.I will check your references to make this work.

Regarding using `GIT_TAG`, the webapp doesn't have a direct relation with this, we would have to always manually update the webapp version even when it has no updates to be related to the `GIT_TAG`. We might find a solution to this, but at the moment, I didn't. I'm happy to join a call to explain these limitations further and try to get some ideas from you on how to overcome them.

2024-12-02 18:51 UTC, sandromello commented on .github/workflows/release.yml
> +        run: export WEBAPP_VERSION=$(awk -F"'" '{printf "%s", $2}' webapp/src/webapp/version.js)
So if you want to maintain this behavior, you'll need to extract the artifact and parse the version as you did and append into the file `$GITHUB_ENV`

2024-12-02 22:26 UTC, mtmr0x commented on .github/workflows/release.yml
> +        run: export WEBAPP_VERSION=$(awk -F"'" '{printf "%s", $2}' webapp/src/webapp/version.js)
seems complicated to explain. I will talk to Rogerio and maybe we do it manually for every release of the webapp then

2024-12-03 00:58 UTC, mtmr0x commented on .github/workflows/release.yml
> +        run: export WEBAPP_VERSION=$(awk -F"'" '{printf "%s", $2}' webapp/src/webapp/version.js)
oh got it! Yeah, I will do that and also do the same implementation on another line in this file for amd64, I just realised I'm doing only for arm64.

2024-12-03 17:28 UTC, sandromello requested changes
Any of these changes won't work @mtmr0x. The version won't be available in the `publish-release` step which requires this information.

You need to extract the version in the `publish-release` step instead. Let me know if you need help with it.

2024-12-04 17:04 UTC, merged